import bgBackoffice from "@/assets/images/backgrounds/bg-backoffice.webp";
import { Layout } from "@/components/layout";
import "@/styles/globals.scss";
import type { Metadata } from "next/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Layout.Body backgroundImgSrc={bgBackoffice.src}>{children}</Layout.Body>;
}
