import { type Prisma } from "@/prisma/generated/client";

export const concerts: Prisma.ConcertCreateInput[] = [
  {
    title: "Solo Recital",
    description: "Kosta Jakic performs a solo recital at salle Henri Le Boeuf",
    date: "2024-05-10T19:00:00.000Z",
    location: "Bozar, salle Henri Le Boeuf",
    timezone: "Europe/Brussels",
    url: "https://www.google.com/",
  },

  {
    title: "Chamber musical recital",
    description: "Kosta Jakic performs a chamber musical recital at the Royal Albert Hall.",
    date: "2024-09-17T20:00:00.000Z",
    location: "De Singel, Antwerp",
    timezone: "Europe/Brussels",
    url: "https://www.google.com/",
  },
  {
    title: "Solo Recital",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-06-22T20:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
    url: "https://www.google.com/",
  },
  {
    title: "Solo Recital",
    description: "Kosta Jakic performs a solo recital at salle Henri Le Boeuf",
    date: "2023-05-10T19:00:00.000Z",
    location: "Bozar, salle Henri Le Boeuf",
    timezone: "Europe/Brussels",
    url: "https://www.google.com/",
  },
  {
    title: "Chamber musical recital",
    description: "Kosta Jakic performs a chamber musical recital at the Royal Albert Hall.",
    date: "2023-05-17T20:20:00.000Z",
    location: "De Singel, Antwerp",
    timezone: "Europe/Brussels",
    url: "https://www.google.com/",
  },
  {
    title: "Solo Recital",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-03-22T20:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
    url: "https://www.google.com/",
    soldout: true,
  },
  {
    title: "Solo Recital 2",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-01-22T20:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
  },
  {
    title: "Solo Recital 3",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-01-22T20:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
  },
  {
    title: "Solo Recital 4",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-01-22T19:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
    url: "https://www.google.com/",
    soldout: true,
  },
  {
    title: "Solo Recital 5",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-01-10T20:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
    url: "https://www.google.com/",
  },
  {
    title: "Solo Recital 6",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-08-22T21:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
  },
  {
    title: "Solo Recital 7",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-03-22T20:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
    url: "https://www.google.com/",
    soldout: true,
  },
  {
    title: "Solo Recital 8",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-08-22T20:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
    url: "https://www.google.com/",
  },
  {
    title: "Solo Recital 9",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-02-22T20:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
    url: "https://www.google.com/",
  },
  {
    title: "Solo Recital 10",
    description: "Kosta Jakic performs a solo recital at the Royal Albert Hall.",
    date: "2024-02-22T22:00:00.000Z",
    location: "Carnegie Hall, New York",
    timezone: "America/New_York",
  },
];
